# Generated by Django 3.1.7 on 2021-05-11 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0002_auto_20210504_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.DateField(),
        ),
    ]
