# Generated by Django 3.1.7 on 2021-05-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0005_auto_20210511_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='year',
        ),
    ]
