# Generated by Django 3.1.7 on 2021-05-18 10:39

from django.db import migrations, models
import khata.models


class Migration(migrations.Migration):

    dependencies = [
        ('khata', '0006_remove_post_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/default.jpg', upload_to=khata.models.upload_to, verbose_name='Image'),
        ),
    ]
